name: GenerateDocumentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:          
      - name: Checkout SdnDiagnostics
        uses: actions/checkout@v2
        with:
          path: main

      - name: Build SdnDiagnostics Module
        run: |
          .\main\.build\build.ps1
        shell: powershell
    
      - name: Generate Documentation
        run: |
          .\main\.build\utilities\generate-documentation.ps1
        shell: powershell

      - name: Checkout SdnDiagnostics.Wiki
        uses: actions/checkout@v2
        with:
          repository: microsoft/SdnDiagnostics.wiki.git
          ref: main
          path: SdnDiagnostics.Wiki

      - name: Copy Documentation to SdnDiagnostics.Wiki
        shell: powershell
        run: |
          Get-ChildItem
          Copy-Item -Path ".\main\.documentation\*" -Include *.md -Destination ".\SdnDiagnostics.Wiki\SdnDiagnostics.Wiki\" -Force -Verbose
      
      - name: Commit to SdnDiagnostics.Wiki
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./\*.md
          git commit -m "Auto-Updated Documentation"
      
      - name: Push to SdnDiagnostics.Wiki
        run: |
          git push
